version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fesajo-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__FesajoStudiosDb=Server=sqlserver;Database=FesajoStudios;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

volumes:
  sql_data:
